### ISSUE TITLE
same assignment is executed twice

### ISSUE THREAD

**Issue by slavah264** [atomnuker/aom#1]
In the function 'set_good_speed_features_framesize_independent', in the section 'if (speed >= 7)' 
the assignment 
    sf->default_min_partition_size = BLOCK_8X8;
is executed twice (line 273 and line 286)

**Comment by atomnuker** [comment]
Fixed in upstream
Next time report issues like that to the main issue tracker at https://bugs.chromium.org/p/aomedia/issues/list
